name: 'PyCharm Python Security Scanner'
author: 'Anthony Shaw'
description: 'Scan your Python Code for security issues'
inputs:
  path:
    description: 'Subdirectory to scan within workdir'
    required: false
    default: '.'
  profile:
    description: 'Path to an inspection profile XML file'
    required: false
    default: '/sources/SecurityInspectionProfile.xml'
  fail_on_warnings:
    description: 'Fail the task if warnings were found in the code'
    required: false
    default: "no"
outputs:
  result:
    description: 'Results from the scan'
runs:
  using: 'docker'
  image: '.github/actions/Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.profile }}
    - ${{ inputs.fail_on_warnings }}
branding:
  icon: 'lock'
  color: 'blue'
