name: 'PyCharm Python Security Scanner'
author: 'Anthony Shaw'
description: 'Scan your Python Code for security issues'
inputs:
  path:
    description: 'Project Directory'
    required: false
    default: '.'
  profile:
    description: 'Path to an inspection profile XML file'
    required: false
    default: '/sources/SecurityInspectionProfile.xml'
  fail_on_warnings:
    description: 'Fail the task if warnings were found in the code'
    required: false
    default: "no"
  source:
    description: 'Subdirectory within path containing Python source'
    required: false
    default: '.'
  requirements:
    description: 'File containing a list of Python packages to be installed before scanning'
    required: false
    default: 'requirements.txt'
outputs:
  result:
    description: 'Results from the scan'
runs:
  using: 'docker'
  image: '.github/actions/Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.profile }}
    - ${{ inputs.fail_on_warnings }}
    - ${{ inputs.source }}
    - ${{ inputs.requirements }}
branding:
  icon: 'lock'
  color: 'blue'
